name: GameCI Template 🎮

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  readmeWorkflow:
    name: Readme Workflow ✨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Projet AR/Library
          key: Library-test

      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
      #  with:
      #    projectPath: test-projects/test-project

      # Build
      - name: Unity - Builder
        uses: game-ci/unity-builder@v2.0-alpha-13
        with:
          projectPath: Projet AR
          targetPlatform: Android



      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Projet AR/build
          unityVersion: 2020.1.1f1
